<?php
    $config["mysqlServer"] = 'localhost';
    $config["mysqlUser"] = 'root';
    $config["mysqlPassword"] = 'peretnep';
    $config["mysqlName"] = 'penterepmail';
    
    $config["version"] = "0.8";
    $config["appname"] = "PenterepMail";
    $config["domain"] = "penterepmail.loc";
    $config["website"] = "penterep.com";
    $config["imap_server"] = "{penterepmail.loc/novalidate-cert}";
    $config["imap"] = "penterepmail.loc";
    $config["operator"] = "HACKER Consulting s.r.o.";
    $config["address1"] = "Luběnice 65";
    $config["address2"] = "783 46 Luběnice";
    $config["admin_login"] = "admin";
    $config["admin_name"] = "Administrator";
    $config["external_url"] = "https://www.penterep.com";
    $config["facebook"] = "https://www.facebook.com/Penterep";
    $config["link_download"] = "https://www.penterep.com";
?>